file_list:
  - src/*.vhd
rule:
  global:
    indentSize: 2
  constant_004: # names
    case: upper
  constant_015: # prefix
    disable: false
    prefixes: ["C_"]
  generic_007: # names
    case: upper
  generic_020: # prefix "G_"
    disable: false
  port_010: # names
    case: lower
  port_011: # prefix
    disable: false
    prefixes: ["i", "o"]
  instantiation_011: # port names
    case: lower
  instantiation_016: # generic names
    case: upper
  signal_007: # default initialization
    disable: true
  subtype_004: # prefix
    disable: false
  type_015: # prefix
    disable: false
