name: synthesis

on: [push, pull_request]

jobs:
  synthesis:
    runs-on: ubuntu-latest
    container: hdlc/impl:ecp5
    steps:
      - uses: actions/checkout@v2
      - name: Run synthesis
        run: syn/synth.sh .
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: build/aes.json
