name: testsuite

on: [push, pull_request]

jobs:
  container:
    runs-on: ubuntu-latest
    container: ghdl/vunit:gcc-master
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install python3-pycryptodome
      - name: Run tests
        run: |
          cd sim/vunit/
          ./run.py
      - uses: codecov/codecov-action@v1
        with:
          file: sim/vunit/coverage.info
